disabled_rules: # rule identifiers to exclude from running 
  - control_statement
  - line_length
  - nesting
  - function_parameter_count
  - function_body_length
  - todo
  - vertical_whitespace
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation # las llaves de cierre deben de estar tabuladas al mismo nivel donde ha sido declarado el closure.
  - closure_spacing # Cada closure debe tener un espacio dentro de cada {}
  - conditional_returns_on_newline # el return siempre debe de ir en una nueva línea.
  - empty_count # No permite usar el .count para compara con 0, debes usar isEmpty
  - fatal_error_message
  - first_where # filtar y retornar el primer valor encontrado
  - multiline_arguments # los argumentos deben de estar en la misma línea o una por línea
  - multiline_parameters # los parametros deben de estar en la misma línea o una por línea
  - object_literal # usar los objetos literales
  - operator_usage_whitespace # espacio entre valores y operadores.
  - sorted_first_last # usar min() y max() sobre sorterd().first o sorted().last
  - sorted_imports # declarar los import alfabeticamente
  - switch_case_on_newline # cases deberían estar en una nueva líena
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - NeoAuto
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - 
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 700
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
#  excluded: iPhone # excluded via string
  excluded: # excluded via string array
    - iPhone
    - FBShimmeringView
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - FBShimmeringView
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)